services:
  postgres:
    container_name: kyalo-postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-boot-network

  spring-boot-app:
    container_name: demo-app
    image: spring/demo
    ports:
      - "8088:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  spring-boot-network:
    driver: bridge